version: '3'
services:
  php-apache:
    build: .
    ports:
    - 8001:80
    volumes:
    - /Users/grzegorzkasperek/Sites/utility/docker/index.html:/var/www/html/index.html

  mariadb:
    image: mariadb:${MARIA_DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mariadb:db
    ports:
    - 8002:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}