version: '3'
services:
  php-apache:
    build:
      context: .
    ports:
    - 8001:80

  mariadb:
    image: mariadb:${MARIA_DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mariadb:db
    ports:
    - 8002:80
    environment:
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}